# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FlightCalculator
                                 A QGIS plugin
 This plugin calculates the distance, time take and estimated fuel burn for a line dataset.  
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-07-19
        copyright            : (C) 2024 by Elena Field/British Antarctic Survey
        email                : eleeld@bas.ac.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Elena Field/British Antarctic Survey'
__date__ = '2024-07-19'
__copyright__ = '(C) 2024 by Elena Field/British Antarctic Survey'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FlightCalculator class from file FlightCalculator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .flight_calculator import FlightCalculatorPlugin
    return FlightCalculatorPlugin(iface)
